# Generated by Django 4.1.7 on 2023-03-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('codigo', models.IntegerField(max_length=20)),
                ('precio', models.FloatField(max_length=20)),
            ],
        ),
    ]
