# Generated by Django 4.1.7 on 2023-03-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_compras_codigo_alter_compras_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('correo', models.EmailField(max_length=254)),
                ('edad', models.FloatField()),
            ],
        ),
    ]
